apiVersion: v1
kind: Secret
metadata:
  name: rootcreds
type: Opaque
data:
  username: Y249RGlyZWN0b3J5IE1hbmFnZXI=
  password: c2VjcmV0MTIzNA==
---
apiVersion: v1
data:
  ZK: "external"
  ZK_CONN_STR: "zookeeper:2181" #this should match the service name from zk deployment(<service_name>.<namespace>.2181)
  ZK_CLUSTER: "fid"
  LICENSE: "<Your_License_Key>"
kind: ConfigMap
metadata:
  labels:
    role: fid
  name: fid-environment-variables
