apiVersion: v1
kind: Secret
metadata:
  name: rootcreds
type: Opaque
data:
  username: Y249RGlyZWN0b3J5IE1hbmFnZXI=
  password: c2VjcmV0MTIzNA==
---
apiVersion: v1
data:
  ZK: "external"
  ZK_CONN_STR: "myzk:2181" #this should match the service name from zk deployment
  ZK_CLUSTER: "fid"
  LICENSE: "{rlib}x9TJ257S1cLYy5fat9TY0cLk2b6v29HSv9TT19PT6cDU2dyRtdDRldHg47Dkyt2gxMLI0sLc6LvdzJXXy9HJpsbk1bibzOHTu9PF3crd4omfn5iUh5CWmZOfoLXTpJmkgqOUnZSbpnyfl5aTgpKblpmwpo2crJ2ohqKUmZGepHykl5XGxMbF3crd4qDY1M7WxsLR2Z6fqn2moJmYhpiVmZaeoLnQ37fStsbXppg="
kind: ConfigMap
metadata:
  labels:
    role: fid
  name: fid-environment-variables