apiVersion: v1
kind: Secret
metadata:
  name: fidrootcreds
type: Opaque
data:
  username: Y249RGlyZWN0b3J5IE1hbmFnZXI=
  password: c2VjcmV0MTIzNA==
---
apiVersion: v1
data:
  CLUSTER: "new"
  ZK: "local"
  ZK_CLUSTER: "fid"
  ZK_PASSWORD: "secret1234"
  LICENSE: "<Your_License_Key>"
kind: ConfigMap
metadata:
  labels:
    role: fid
  name: fid-environment-variables
---
apiVersion: v1
kind: Service
metadata:
  name: fid
  labels:
    app: fid
spec:
  ports:
    - port: 9100
      name: admin-http
    - port: 2389
      name: ldap
    - port: 2636
      name: ldaps
  selector:
    app: fid
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fid-cp
  labels:
    app: fid-cp
spec:
  ports:
    - port: 7070
      name: cp-http
    - port: 7171
      name: cp-https
    - port: 8089
      name: http
    - port: 8090
      name: https
  selector:
    statefulset.kubernetes.io/pod-name: fid-0
  type: LoadBalancer
--  

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fid
  labels:
    kubernetes.io/os: linux
spec:
  selector:
    matchLabels:
      app: fid # has to match .spec.template.metadata.labels
  serviceName: "fid"
  replicas: 1 # by default is 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fid # has to match .spec.selector.matchLabels
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: fid
          image: anikhet/ib-fidimg
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "echo Hello from the fid postStart handler > /opt/radiantone/vds/lifecycle.txt",
                  ]
            preStop:
              exec:
                #              command: ["/opt/radiantone/vds/bin/advanced/cluster.sh","detach"]
                command: ["/opt/radiantone/vds/bin/stopVDSServer.sh"]
          ports:
            - containerPort: 2181
              name: zk-client
            - containerPort: 7070
              name: cp-http
            - containerPort: 7171
              name: cp-https
            - containerPort: 9100
              name: admin-http
            - containerPort: 9101
              name: admin-https
            - containerPort: 2389
              name: ldap
            - containerPort: 2636
              name: ldaps
            - containerPort: 8089
              name: http
            - containerPort: 8090
              name: https
          readinessProbe:
            tcpSocket:
              port: 2389
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 5
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 9100
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 5
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: fid-environment-variables
          env:
            - name: ZK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fidrootcreds
                  key: password
          volumeMounts:
            - name: r1-pvc
              mountPath: /opt/radiantone/vds
          command: ["/bin/sh", "-c"]
          args:
            [
              "if [ $HOSTNAME != fid-0 ]; then export CLUSTER=join; export ZK_CONN_STR=fid-0.fid.fid-nginx.svc.cluster.local:2181;fi;./run.sh fg", # replace namespace fid-nginx with namespace where it is been deployed
            ]
      nodeSelector:
        kubernetes.io/os: linux      
      volumes:
      - name: r1-pvc
        emptyDir: {}
