apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      name: zookeeper-client
    - port: 8080
      name: zookeeper-http
  selector:
    app: zookeeper
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    kubernetes.io/os: linux
spec:
  selector:
    matchLabels:
      app: zookeeper # has to match .spec.template.metadata.labels
  serviceName: "zookeeper"
  replicas: 3
  template:
    metadata:
      labels:
        app: zookeeper # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: zookeeper
          image: radiantone/zookeeper:3.5.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
              name: zk-client
            - containerPort: 2888
              name: zk-ensemble
            - containerPort: 3888
              name: zk-election
            - containerPort: 8080
              name: zk-admin
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - name: zookeeper-pvc
              mountPath: /opt/radiantone/rli-zookeeper-external
          env:
            - name: CLIENT_PORT
              value: "2181"
            - name: ENSEMBLE_PORT
              value: "2888"
            - name: LEADERRELECTION_PORT
              value: "3888"
            - name: ADMIN_PORT
              value: "8080"
            - name: ZOOKEEPER_FLEET_SIZE
              value: "3"
            - name: JAVA_HOME
              value: "/opt/radiantone/rli-zookeeper-external/jdk/jre/"
          command: ["/bin/sh", "-c"]
          args: ["/opt/radiantone/run.sh"]
        - name: fluentd
          image: vamzi/fluentd
          imagePullPolicy: Always
          env:
          - name: FLUENTD_CONF
            value: /etc/fluentd-config/fluentd.conf
          volumeMounts:
          - name: zookeeper-pvc
            mountPath: /var/log/zookeeper
            subPath: zookeeper/logs
          - name: fluentd-config
            mountPath: /etc/fluentd-config
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: zookeeper-pvc
          emptyDir: {}
        - name: fluentd-config
          configMap:
            name: fluentd-zk-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-zk-config
data:
  fluentd.conf: |
    <source>
      @type tail
      read_from_head true
      path /var/log/zookeeper/zookeeper.log
      pos_file /var/log/zookeeper/zookeeperlog.pos
      tag zookeeper.log
      <parse>
        @type multiline_grok
        grok_pattern %{TIMESTAMP_ISO8601:timestamp} \[myid:%{NUMBER:zk_id}\] - %{WORD:log_level} \[%{GREEDYDATA:thread_name}\] - %{GREEDYDATA:message}
        multiline_start_regexp /\d{4}-\d{1,2}-\d{1,2}/
      </parse>
    </source>

    <filter zookeeper.log>
      @type record_transformer
      <record>
      hostname ${hostname}
      </record>
    </filter>

    <match zookeeper.log>
      @type elasticsearch
      host elasticsearch.logging
      port 9200
      logstash_format true
      logstash_prefix zookeeper.log
    </match>

