apiVersion: apps/v1
kind: Deployment
metadata:
  name: authrate
spec:
  selector:
    matchLabels:
      app: authrate
  replicas: 1
  template:
    metadata:
      labels:
        app: authrate
    spec:
      initContainers:
        - name: check-fid
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-c"," apk add -q --no-cache wait4ports && wait4ports tcp://fid.fid-demo.svc.cluster.local:2389"]
          securityContext:
            privileged: true
      containers:
        - name: authrate
          image: pingidentity/ldap-sdk-tools:edge
          imagePullPolicy: Always
          command:
            [
              "sh",
              "-c",
              'authrate -h fid.fid-demo.svc.cluster.local -p 2389 -D uid=operator,ou=globalusers,cn=config -w secret1234 -b dc=lg100k -f "(uid=[1-1000])" -C secret --numThreads 1',
            ]
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: modrate
spec:
  selector:
    matchLabels:
      app: modrate
  replicas: 1
  template:
    metadata:
      labels:
        app: modrate
    spec:
      initContainers:
        - name: check-fid
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-c"," apk add -q --no-cache wait4ports && wait4ports tcp://fid.fid-demo.svc.cluster.local:2389"]
          securityContext:
            privileged: true
      containers:
        - name: modrate
          image: pingidentity/ldap-sdk-tools:edge
          imagePullPolicy: Always
          command:
            [
              "sh",
              "-c",
              'wait-for fid.fid-demo.svc.cluster.local:2389 -t 900 -- modrate -h fid.fid-demo.svc.cluster.local -p 2389 -D uid=operator,ou=globalusers,cn=config -w secret1234 --entryDN "uid=[1-1000],dc=lg100k" --attribute description --valueLength 10 --numThreads 1',
            ]
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchrate
spec:
  selector:
    matchLabels:
      app: searchrate
  replicas: 1
  template:
    metadata:
      labels:
        app: searchrate
    spec:
      initContainers:
        - name: check-fid
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh","-c"," apk add -q --no-cache wait4ports && wait4ports tcp://fid.fid-demo.svc.cluster.local:2389" ]
          securityContext:
            privileged: true
        - name: get-jmx
          image: radial/busyboxplus:curl
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              "mkdir -p /home/jmx && cd /home/jmx && curl -O https://raw.githubusercontent.com/radiantlogic-devops/docker-compose/master/05-monitoring-stack/configs/jmeter/ldap.jmx",
            ]
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /home/jmx
              name: jmx
      containers:
        - name: searchrate
          image: pingidentity/apache-jmeter:latest
          imagePullPolicy: Always
          env:
            - name: SERVER_PROFILE_URL
              value: "https://github.com/ping-devops-program/anydevops"
            - name: SERVER_PROFILE_PATH
              value: "perf/profiles/jmeter"
            - name: STARTUP_FOREGROUND_OPTS
              value: "--nongui -t /home/jmx/ldap.jmx -Jhost=fid.fid-demo.svc.cluster.local -Jport=2389 -JthreadCount=10 -Jramp=2"
          command: ["/bin/sh","-c","wait-for fid.fid-demo.svc.cluster.local:2389 -t 900 -- entrypoint.sh start-server"]
          volumeMounts:
            - mountPath: /home/jmx
              name: jmx
      volumes:
        - name: jmx
          emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
